services:
  postgres:
    image: postgres:15
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser          # Nombre del usuario
      POSTGRES_PASSWORD: mypassword  # Contraseña del usuario
      POSTGRES_DB: LeadBoardDb        # Nombre de la base de datos inicial
    ports:
      - "5432:5432"                  # Exponer puerto para conexión local